version: '3'

services:
  app:
    container_name: "go-app"
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile
      args:
        # Update the VARIANT arg to pick a version of Go: 1, 1.16, 1.15
        VARIANT: 1

        # Options
        INSTALL_NODE: false
        NODE_VERSION: "lts/*"

    init: true
    networks:
      - container_link
    volumes:
      # Forwards the local Docker socket to the container.
      - /var/run/docker.sock:/var/run/docker-host.sock
      # Update this to wherever you want VS Code to mount the folder of your project
      - ..:/ws:cached

    # Overrides default command so things don't shut down after the process ends.
    entrypoint: /usr/local/share/docker-init.sh
    command: sleep infinity

    # Uncomment the next four lines if you will use a ptrace-based debuggers like C++, Go, and Rust.
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    # Uncomment the next line to use a non-root user for all processes.
    # user: vscode

  db:
    container_name: mongo
    image: mongo
    # restart: on-failure
    networks:
      - container_link
    expose:
      - 27017
    volumes:
      - mongo-store:/data/db
      - ./mongo/conf:/data/configdb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mongo

  # Use "forwardPorts" in **devcontainer.json** to forward an app port locally.
  # (Adding the "ports" property to this file will not forward from a Codespace.)

networks:
  default:
    name: bridge

  container_link:
    name: docker.internal
    driver: bridge
    ipam:
      driver: default

volumes:
  mongo-store:
    external: true
